# Generated by Django 5.2.8 on 2025-11-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_banner_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
