# Generated by Django 5.2.8 on 2025-11-11 12:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_banner_options_remove_banner_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
