# Generated by Django 5.2.8 on 2025-11-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_service_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Content',
                'verbose_name_plural': 'Dashboard Contents',
            },
        ),
        migrations.CreateModel(
            name='DashboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('file', models.ImageField(upload_to='content/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='salon.dashboardcontent')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('content', 'key')},
            },
        ),
    ]
