# Generated by Django 5.2.8 on 2025-11-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
