# Generated by Django 5.2.8 on 2025-11-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
